sudo: required

services:
  - mongodb
  - docker

before_install:
 - docker pull quay.io/cayleygraph/cayley
 - docker run -v $PWD/travis/:/data -p 64210:64210 -d quay.io/cayleygraph/cayley

language: node_js
node_js:
  - 6.9.1

notifications:
  email: true

